/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TablasRouteImport } from './routes/tablas'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as AbrirMesaRouteImport } from './routes/abrir-mesa'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MesaIdIndexRouteImport } from './routes/mesa.$id.index'
import { Route as MesaIdJugarRouteImport } from './routes/mesa.$id.jugar'

const TablasRoute = TablasRouteImport.update({
  id: '/tablas',
  path: '/tablas',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AbrirMesaRoute = AbrirMesaRouteImport.update({
  id: '/abrir-mesa',
  path: '/abrir-mesa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MesaIdIndexRoute = MesaIdIndexRouteImport.update({
  id: '/mesa/$id/',
  path: '/mesa/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const MesaIdJugarRoute = MesaIdJugarRouteImport.update({
  id: '/mesa/$id/jugar',
  path: '/mesa/$id/jugar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abrir-mesa': typeof AbrirMesaRoute
  '/menu': typeof MenuRoute
  '/tablas': typeof TablasRoute
  '/mesa/$id/jugar': typeof MesaIdJugarRoute
  '/mesa/$id/': typeof MesaIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abrir-mesa': typeof AbrirMesaRoute
  '/menu': typeof MenuRoute
  '/tablas': typeof TablasRoute
  '/mesa/$id/jugar': typeof MesaIdJugarRoute
  '/mesa/$id': typeof MesaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abrir-mesa': typeof AbrirMesaRoute
  '/menu': typeof MenuRoute
  '/tablas': typeof TablasRoute
  '/mesa/$id/jugar': typeof MesaIdJugarRoute
  '/mesa/$id/': typeof MesaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abrir-mesa'
    | '/menu'
    | '/tablas'
    | '/mesa/$id/jugar'
    | '/mesa/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abrir-mesa'
    | '/menu'
    | '/tablas'
    | '/mesa/$id/jugar'
    | '/mesa/$id'
  id:
    | '__root__'
    | '/'
    | '/abrir-mesa'
    | '/menu'
    | '/tablas'
    | '/mesa/$id/jugar'
    | '/mesa/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbrirMesaRoute: typeof AbrirMesaRoute
  MenuRoute: typeof MenuRoute
  TablasRoute: typeof TablasRoute
  MesaIdJugarRoute: typeof MesaIdJugarRoute
  MesaIdIndexRoute: typeof MesaIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tablas': {
      id: '/tablas'
      path: '/tablas'
      fullPath: '/tablas'
      preLoaderRoute: typeof TablasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abrir-mesa': {
      id: '/abrir-mesa'
      path: '/abrir-mesa'
      fullPath: '/abrir-mesa'
      preLoaderRoute: typeof AbrirMesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesa/$id/': {
      id: '/mesa/$id/'
      path: '/mesa/$id'
      fullPath: '/mesa/$id/'
      preLoaderRoute: typeof MesaIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesa/$id/jugar': {
      id: '/mesa/$id/jugar'
      path: '/mesa/$id/jugar'
      fullPath: '/mesa/$id/jugar'
      preLoaderRoute: typeof MesaIdJugarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbrirMesaRoute: AbrirMesaRoute,
  MenuRoute: MenuRoute,
  TablasRoute: TablasRoute,
  MesaIdJugarRoute: MesaIdJugarRoute,
  MesaIdIndexRoute: MesaIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
